FROM apache/airflow:2.9.3

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends openjdk-17-jdk-headless procps && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
USER airflow

RUN pip install --no-cache-dir \
    pandas \
    scikit-learn \
    "mlflow>=3.2.0,<3.3.0" \
    xgboost \
    requests \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.3/constraints-3.12.txt"

# pyspark installé séparément, SANS le fichier de contraintes Airflow (qui pin
# pyspark à 3.5.1) -> on veut 3.5.8 pour matcher exactement l'image spark:3.5.8
# de nos manifests K8s.
RUN pip install --no-cache-dir pyspark==3.5.8

RUN pip install --no-cache-dir --timeout=180 --retries=10 \
    torch --index-url https://download.pytorch.org/whl/cpu

RUN pip install --no-cache-dir --timeout=180 --retries=10 ctgan==0.10.2