FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --timeout=180 --retries=10 -r requirements.txt

COPY main.py .

COPY model/model.pkl /app/model/model.pkl
COPY model/feature_columns.json /app/model/feature_columns.json
COPY model/preprocessing_scaler.pkl /app/model/preprocessing_scaler.pkl

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]